/* eslint-disable */
/* protocol buffer code generated by https://protip.dev */

/**
 * @fileoverview gRPC-Web generated client stub for testing
 * @enhanceable
 * @public
 */

// GENERATED CODE -- DO NOT EDIT!


import * as grpcWeb from 'grpc-web';

import {
  TestRequest,
  TestResponse} from './test_pb';

export class TestClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: string; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: string; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname;
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodInfoTest = new grpcWeb.AbstractClientBase.MethodInfo(
    TestResponse,
    (request: TestRequest) => {
      return request.serializeBinary();
    },
    TestResponse.deserializeBinary
  );

  test(
    request: TestRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.Error,
               response: TestResponse) => void) {
    return this.client_.rpcCall(
      this.hostname_ +
        '/testing.Test/Test',
      request,
      metadata || {},
      this.methodInfoTest,
      callback);
  }

}

